db:
	python manage.py makemigrations
	python manage.py migrate

server:
	python manage.py runserver

All:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py runserver

make push:
	./scripts.sh

test:
	python manage.py test